### ISSUE TITLE
Typo?!

### ISSUE THREAD

**Issue by steff94** [Commifreak/unraid-appdata.backup#1]
https://github.com/Commifreak/unraid-appdata.backup/blob/4f2aa388855013bedc345b3a8cfadf6c7d2738d2/src/scripts/backup.php#L66

Currently:     "ABHelper::backupLog("Destination is available or not writeable!", ABHelper::LOGLEVEL_ERR);"
Should?:     ABHelper::backupLog("Destination is **un**available or not writeable!", ABHelper::LOGLEVEL_ERR);

Best regards

**Comment by Commifreak** [comment]
You are right!
