### ISSUE TITLE
FEATURE REQUEST: Show Backup Time Duration

### ISSUE THREAD

**Issue by hernandito** [Commifreak/unraid-appdata.backup#10]
Similar to how it shows how long it it took to stop an individual container; it would be AWESOME to show how long the entire backup took for the container. This would help determine if some dockers are worth excluding... like Plex or Emby.

![image](https://github.com/Commifreak/unraid-appdata.backup/assets/787317/e5971cd5-18ee-4893-aff1-ae98551b4c86)

It would also be nice to see the total duration at the end of the complete backup process.

p.s.. Please forgive the css tweak see in my screencap.

**Comment by Commifreak** [comment]
Added info for backup and verification:

![grafik](https://github.com/user-attachments/assets/fa6986a3-2042-4e6c-9de8-6f5d04b6b9f3)
