### ISSUE TITLE
Invert "Dont stop container?" to remove the double negative

### ISSUE THREAD

**Issue by othyn** [Commifreak/unraid-appdata.backup#11]
This is a subjective thing, but the phrasing of "Dont stop container?" with the default being "No" leads to having to unpack the double negative to work out what that is actually saying and therefor doing.

Its quite hard to break it down and actually think what its doing. I personally find it really confusing and it took longer than I care to admit to walk through it and concretely workout if I want the container to stop or not.

> "No" to the question "Dont stop container?" means "No, do not stop the container," implying that the container should continue running.

It's weird, and doesn't flow through the brain very well. Like eating dry pasta, technically you can, but it feels wrong doing so, just from the crunch alone.

The much easier option would be to have the phrasing read "Stop the container?" and defaulting it to "Yes", as then the option is a really simple question and answer that requires no further thought or unpacking the logic inversion on the double negative.

> "Stop the container?" with the answer "No" means the container should be left running.

I get this would require a logic inversion/migration step for existing installations, and handling the migration of that is not easy, but it would really _really_ help keep the UX intuitive.

**Comment by Commifreak** [comment]
Maybe a compromise?

![grafik](https://github.com/Commifreak/unraid-appdata.backup/assets/87267/b581ff4b-7b92-44fb-acc6-d4abc1449e1b)

**Comment by othyn** [comment]
Yeah that would also work - and remove the migration requirement 👍
