### ISSUE TITLE
Post-run script?

### ISSUE THREAD

**Issue by nobodyspecial** [Commifreak/unraid-appdata.backup#14]
I have noticed that the "Post-run script" is running before the "Some extra options" is run. Is there a way to change this behavior?

**Comment by Commifreak** [comment]
Thats already fixes since latest stables. Please recheck and open if something is still not working as expected.

**Comment by nobodyspecial** [comment]
I just updated to plugin version 2024.02.06b and tried a scheduled backup and a manual backup and in both cases the "Post-run script" executes before the "Include extra files/folders" option. 

I have a remote device running a docker that I need to stop during the backup and start after it finishes. The "Post-run script" is starting this remote docker as the files are being backed up causing "tar creation failed!" and "file changed as we read it;" errors.

**Comment by nobodyspecial** [comment]
Thanks for your help. I'll have to review my config.
