### ISSUE TITLE
Feature Request: --ignore-case

### ISSUE THREAD

**Issue by nemchik** [Commifreak/unraid-appdata.backup#26]
It would be great to have the ability to toggle case insensitivity in the pattern matching for file/folder names.

`--ignore-case` should be the option that does it.

Reason:
I have some apps that make a folder named `Backup` and others that make `backup` and rather than having two exclusions it would be great to just ignore case for file/folder name matching.

**Comment by Commifreak** [comment]
The upcoming beta should do this.
