### ISSUE TITLE
Updating containers doesn't work

### ISSUE THREAD

**Issue by KnifeFed** [Commifreak/unraid-appdata.backup#3]
Since I installed the plugin, it has never updated a container. When checking for updates, it just says "No update available" for every container.

Debug log ID: `96c0a5aa-61ad-4fae-9066-f6ba4400974e`.

On a related note, according to the logs, it seems that the containers are updated after all backups have been completed. For efficiency, it would be great if checking for updates is performed first to see which containers need updating, then after each container is backed up, it gets updated before it's started again. That way, the containers only have to be stopped/started once. What do you think?

**Comment by Commifreak** [comment]
Yea, that was already posted in the forums. And I believe I know where the bug lives. Releasing an update asap.

**Comment by Commifreak** [comment]
Looking at your debug log shows me, that none of you update-enabled containers need any update. Are you sure that one of them need an update?

**Comment by KnifeFed** [comment]
Yes, several of them have updates available.

**Comment by Commifreak** [comment]
Please post at least one example.

**Comment by KnifeFed** [comment]
- autoscan 
- bazarr 
- cloudflareddns 
- cross-seed 
- Dozzle 
- filebot-node 
- PlexAutoSkip 
- TimeMachine

**Comment by Commifreak** [comment]
Fixed in 24310fa55a403f7d6307cfbd5a769238ddb8c6ee

**Comment by KnifeFed** [comment]
Awesome, thank you!
