### ISSUE TITLE
Backup number problem

### ISSUE THREAD

**Issue by tony77682** [Commifreak/unraid-appdata.backup#30]
Good morning,
I have a problem with selecting the number of backups to keep.
it does not erase old backups.
As a result, the backup HDD is full and nothing is backed up.

help me

**Comment by Commifreak** [comment]
Are the backup suffixed with `-failed`?

**Comment by tony77682** [comment]
actually I have a failed at the end of the file, this is because of the container which I cannot stop.

does the problem come from this?

**Comment by Commifreak** [comment]
I think so. Check the log.

Backups with `-failed` does not get deleted automatically.

**Comment by tony77682** [comment]
I'll do some testing and see if that fixes the problem. but it's a shame that this poses a problem

**Comment by tony77682** [comment]
I confirm that the problem comes from the failed folder. is it possible to fix this?

**Comment by Commifreak** [comment]
I still dont know what your issue is. Start a run and share the debug ID.

**Comment by tony77682** [comment]
the problem is that if it says failed on a backup folder, it is not deleted with the command "Delete backups if older than x days:"

**Comment by Commifreak** [comment]
Yes. Then fix the issue which causes the backup to fail and delete the backups with „failed“ suffix manually.
