### ISSUE TITLE
Grouped containers getting backed up multiple times

### ISSUE THREAD

**Issue by DavidDriessen** [Commifreak/unraid-appdata.backup#32]
**Version:** 2024.03.17
**UnraidVersion:** 6.12.11

Grouped containers based on there dependencies. Example mariadb, nextcloud, other apps that use mariadb.
When I run the backup, I see multiple log lines saying "Backing up nextcloud". I noticed this for all my grouped containers.

Further more, I have Backup type set to stop,backup,start for each container. But when I use the grouping all containers get stopped anyway.

[ab.debug.log](https://github.com/user-attachments/files/16487190/ab.debug.log)

**Comment by Commifreak** [comment]
> Further more, I have Backup type set to stop,backup,start for each container. But when I use the grouping all containers get stopped anyway.

Thats normal and intended.

**Comment by DavidDriessen** [comment]
Shouldn't only the ones in the group be stopped?

**Comment by DavidDriessen** [comment]
After some twitting I found out it only does is when there is a group that has all containers  set to skip. When I removed that group it is working correctly. The containers in the group stop, containers get backed up and the containers in the group start again. So with the next group.
