### ISSUE TITLE
make all container backup easier

### ISSUE THREAD

**Issue by realies** [Commifreak/unraid-appdata.backup#4]
I'd like to back up all container appdata without stopping them during the back-up. At the moment, I have to go through all containers manually, remove the skip dropdown, then open an expanding menu and select an option in a dropdown.

It also seems that when 'Save external volumes?' is set to 'No', it would attempt to do that anyway, making it impossible to back up containers that have big mounted volumes.

**Comment by Commifreak** [comment]
So, you basically wish a global setting "Do not stop the container" as a default setting to include all new created containers automatically?

**Comment by realies** [comment]
> So, you basically wish a global setting "Do not stop the container" as a default setting to include all new created containers automatically?

Yes.

**Comment by realies** [comment]
I don't get why it's so difficult to backup all appdata folders for all containers while they are running.
I spent a good amount of time clicking and ignoring volumes to set this up.
And every change to the mounted folders has to be reflected in the backup plugin.

**Comment by Commifreak** [comment]
Its not difficult at all. But inconsistent. You are backing up datas and databases which could be in use. That could lead to inconsistent backups.

> And every change to the mounted folders has to be reflected in the backup plugin.
If you change them yes. Are you playing with your setup every day? Once set and productive it should be working.

**Comment by realies** [comment]
> Its not difficult at all. 
It is, compared to previous versions of the plugin. I did not have to go and tweak everything individually.
> You are backing up datas and databases which could be in use. That could lead to inconsistent backups.
With very fast storage that's less of an issue.
> Are you playing with your setup every day?
I do, very frequently, and having to ignore shares every time is annoying.

There could be an option which only includes cache appdata for every container, instead of excluding everything else.
Likewise for a global toggle that allows you to backup running containers.

**Comment by Commifreak** [comment]
Please test beta `2024.02.08b1` which will get released later today. It gives you the option. Please test and report back if its sufficient.

**Comment by realies** [comment]
@Commifreak, I don't see any "Skip stopping container" option in the UI of AB.Beta.Main.

**Comment by Commifreak** [comment]
Beta version.

**Comment by realies** [comment]
AB.Beta.Main.

**Comment by Commifreak** [comment]
So? Did you installed the current beta and tried it?

**Comment by realies** [comment]
PS: Should I uninstall the non-beta version? Would this make it to the stable version soon?

**Comment by Commifreak** [comment]
> was not searchable in the visible part of the cluttered interface

Yea its a bit messy but there a several settings to show 🤷. Any ideas are appreciated!

The setting is hidden in the Special settings section, which must be clicked to show up.



> Should I uninstall the non-beta version? Would this make it to the stable version soon?

These are two separate plugins. Please keep beta until new prod version arrives if you want to use the option already. Otherwise delete beta. It will be stable within next week hopefully.
