### ISSUE TITLE
Feature Request: additional  docker shut down

### ISSUE THREAD

**Issue by binarygeek119** [Commifreak/unraid-appdata.backup#40]
when it goes to back up i like it to shut down one at a time sure the minimum is offline durning backup.
but i do have some docker that have to work in pairs.
example:
TubeArchivist-ES
TubeArchivist-RedisJSON
TubeArchivist

it will shut down and backup, but it will error out if anything changes during backup. this happens because two of the three are still up and running.

what i like is to be able to apply a override of some kind that says when X docker goes down for backup also shut down Y,Z dockers i would need that to be able to do multiple pairs not just one.
my ideal way would be one when docker X is being backed up it will shut down docker Y,Z but keep docker A,B,C up till its there turn. and not just shut down all pairs all at once.

**Comment by Commifreak** [comment]
Is the grouping feature not working for that case?

**Comment by binarygeek119** [comment]
sorry i didnt know about the grouping settings.
